name: mw_petalinux
services:
  petalinux-base:
    image: mw_petalinux:${PETALINUX_RELEASE}
    user: "${UID}:${GID}"
    build:
      args:
        #PUID: ${PUID}
        #PGID: ${PGID}
        PETALINUX_RELEASE: ${PETALINUX_RELEASE}
        PETALINUX_INSTALLER: ${PETALINUX_INSTALLER}
        UBUNTU_RELEASE: ${UBUNTU_RELEASE}

  petalinux:
    extends: petalinux-base
    volumes:
      - ${PWD}:/work
    tty: true

  petalinux-cache:
    extends: petalinux
    volumes:
      - /opt/yocto:/opt/yocto # For sstate cache
    tty: true

  petalinux-runner:
    extends: petalinux-base
    user: "${RUNNER_PUID}:${RUNNER_PGID}"
    build:
      tags:
        - "mw_petalinux_runner:${PETALINUX_RELEASE}"
