name: mw_petalinux
services:
  petalinux:
    image: mw_petalinux_install:${PETALINUX_RELEASE}
    build:
      tags:
        - "mw_petalinux_install:${PETALINUX_RELEASE}"
      args:
        PUID: ${PUID}
        PGID: ${PGID}
        PETALINUX_RELEASE: ${PETALINUX_RELEASE}
        PETALINUX_INSTALLER: ${PETALINUX_INSTALLER}
        UBUNTU_RELEASE: ${UBUNTU_RELEASE}
    volumes:
      - .:/work

  petalinux-cache:
    extends: petalinux
    volumes:
      - /opt/yocto:/opt/yocto # For sstate cache
